name: hyper_net
description: HyperNet is a Wrapper around Dio that can perform api request with better error handling and easily get the result of any api request.
version: 0.1.0
homepage: https://devtech365.com
repository: https://github.com/risfat/hyper_net
issue_tracker: https://github.com/risfat/hyper_net/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

topics:
    - hypernet
    - dio
    - network
    - api

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  sentry_dio: ^8.13.2
  playx_core: ^0.6.3
  dio_web_adapter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

